/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.1.11-3-g7ef6f317f8"
#endif /* AVUTIL_FFVERSION_H */
